apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-motivator-frontend
  namespace: workout-motivator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workout-motivator-frontend
  template:
    metadata:
      labels:
        app: workout-motivator-frontend
    spec:
      containers:
      - name: workout-motivator-frontend
        image: workoutmotivatoracr.azurecr.io/workout-motivator-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "80"
      imagePullSecrets:
      - name: acr-secret
