apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-motivator-frontend
  namespace: workout-motivator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-motivator-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: workout-motivator-frontend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: workout-motivator-frontend
        image: workoutmotivatoracr.azurecr.io/workout-motivator-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        command: ["nginx", "-g", "daemon off;"]
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "80"
        - name: REACT_APP_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: REACT_APP_FIREBASE_API_KEY
        - name: REACT_APP_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: REACT_APP_FIREBASE_AUTH_DOMAIN
        - name: REACT_APP_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: REACT_APP_FIREBASE_PROJECT_ID
        - name: REACT_APP_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: REACT_APP_FIREBASE_STORAGE_BUCKET
        - name: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        - name: REACT_APP_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: REACT_APP_FIREBASE_APP_ID
        - name: REACT_APP_FIREBASE_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-config
              key: REACT_APP_FIREBASE_MEASUREMENT_ID
