apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workout-motivator-frontend-hpa
  namespace: workout-motivator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workout-motivator-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
