name: Deploy to AKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CLUSTER_NAME: workout-motivator
  CLUSTER_RESOURCE_GROUP: WAP
  NAMESPACE: workout-motivator
  APP_NAME: workout-motivator-frontend
  ACR_NAME: workoutmotivatoracr
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and push image to ACR
        uses: azure/docker-login@v1
        with:
          login-server: workoutmotivatoracr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build . -t workoutmotivatoracr.azurecr.io/workout-motivator-frontend:${{ github.sha }}
          docker build . -t workoutmotivatoracr.azurecr.io/workout-motivator-frontend:latest
          docker push workoutmotivatoracr.azurecr.io/workout-motivator-frontend:${{ github.sha }}
          docker push workoutmotivatoracr.azurecr.io/workout-motivator-frontend:latest
      
      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      
      - name: Create namespace if doesn't exist
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/deployment.yml
            kubernetes/service.yml
          images: |
            workoutmotivatoracr.azurecr.io/workout-motivator-frontend:${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}
          strategy: recreate
