name: K6 Load Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for deployment to be accessible
        timeout-minutes: 5
        run: |
          echo "Waiting for deployment to be accessible..."
          while ! curl -s -o /dev/null -w "%{http_code}" http://20.31.46.9 | grep -q "200"; do
            echo "Deployment not ready yet, waiting 10 seconds..."
            sleep 10
          done
          echo "Deployment is accessible!"

      - name: Run k6 test with Docker
        run: |
          # Add a small initial delay to ensure the service is fully stable
          sleep 15
          docker run --rm -i grafana/k6 run - <k6/homepage.js

      - name: Store test results
        if: always()
        run: |
          echo "Load test complete. Check the logs above for detailed results."
