name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start Test Environment
      run: |
        # Start the frontend in test mode
        npm run start:testenv &
        echo "Frontend started"
        
        # Install and start Firebase emulators
        npm install -g firebase-tools
        firebase emulators:start --only auth &
        echo "Firebase emulator started"
        
        # Wait for both services to be ready
        npx wait-on http://localhost:3000 http://localhost:9099
      env:
        REACT_APP_USE_EMULATORS: true
        CI: true
        
    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: true
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
